M48
; DRILL file {KiCad (6.0.1)} date Sat 29 Jan 2022 10:27:49 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-29T10:27:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X135.575Y-72.03
X140.425Y-72.03
T2
X135.275Y-69.0
X140.725Y-69.0
T0
M30
